apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-svc
  namespace: lab
spec:
  ports:
  - port: 8083
    targetPort: 8083
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-connect-svc
  namespace: lab
subsets:
- addresses:
  - ip: 10.0.2.40
  ports:
  - port: 8083
